# Generated by Django 4.0 on 2022-01-13 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название отдела')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40, verbose_name='Имя')),
                ('surname', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=40, verbose_name='Отчество')),
                ('date_birdth', models.DateTimeField(verbose_name='Дата рождения')),
                ('email', models.CharField(max_length=30, verbose_name='Электронная почта')),
                ('date_job_start', models.DateTimeField(verbose_name='Дата начала работы')),
                ('date_job_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания работы')),
                ('position_at_work', models.CharField(max_length=50, verbose_name='Должность')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.group')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
